### ISSUE TITLE
ユーザ作成APIのドキュメントを仕様通りに修正

### ISSUE THREAD

**Issue by TakumaKurosawa** [TechCafeFreedom/Wantum-server#21]
## 概要
現状JWTトークンをHeaderに受け取り、ユーザを作成しているが、ユーザが入力したプロフィール情報も含めてリクエストされるという仕様に変更されたため、下記のAPI定義を修正する必要がある。
https://stoplight.io/p/docs/gh/techcafefreedom/wantum-server/docs/reference/wantum.v1.0.0.yaml/paths/~1auth~1signup/get?srn=gh/techcafefreedom/wantum-server/docs/reference/wantum.v1.0.0.yaml/paths/~1auth~1signup/get&group=develop

**Comment by sana37** [comment]
grpcに移行することになったためRESTのAPIドキュメントは不要となりました。
